### ISSUE TITLE
Please give proper credit

### ISSUE THREAD

**Issue by sirdoha** [onokatio/Sony-Xperia-XZ2-Sound-System#2]
Hey there, 

Hope you are doing well. I am the original creator of this mod on the XDA Forum. Although you have identified that you are not the author, I would appreciate it if you could at least mention me on the README.md page.

Regards,
@sirdoha

**Comment by onokatio** [comment]
Sorry for that.
I'm going to add your credit to README.md.

**Comment by onokatio** [comment]
Fixed at https://github.com/onokatio/Sony-Xperia-XZ2-Sound-System/commit/05be235abc1f5dcd9cc258b10d57f864c959ad49
